"""Bundle the add-on into one self-contained script for a remote ``bpy`` worker.

Some Blender hosts (Claude's 3D Jutsu worker, render farms, `blender --python -`
over a pipe) will run a single Python string but cannot see this repository.
This packs the modules the scene builder needs into one file that reconstitutes
``model_y`` in ``sys.modules`` and then runs a chosen entry point.

    python3 tools/bundle_for_blender.py --out build/model_y_bundle.py
    python3 tools/bundle_for_blender.py --entry preview --out build/preview.py
"""

from __future__ import annotations

import argparse
import io
import os
import re
import tokenize

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

# Order matters only for readability; the loader resolves imports lazily.
MODULES = [
    ("model_y.specs", "model_y/specs.py"),
    ("model_y.vehicle_sim", "model_y/vehicle_sim.py"),
    ("model_y.grok", "model_y/grok.py"),
    ("model_y.geom.mesh", "model_y/geom/mesh.py"),
    ("model_y.geom.body", "model_y/geom/body.py"),
    ("model_y.geom.wheels", "model_y/geom/wheels.py"),
    ("model_y.geom.lights", "model_y/geom/lights.py"),
    ("model_y.geom.interior", "model_y/geom/interior.py"),
    ("model_y.geom.assemble", "model_y/geom/assemble.py"),
    ("model_y.geom", "model_y/geom/__init__.py"),
    ("model_y.ui.font5x7", "model_y/ui/font5x7.py"),
    ("model_y.ui.raster", "model_y/ui/raster.py"),
    ("model_y.ui.screen", "model_y/ui/screen.py"),
    ("model_y.ui", "model_y/ui/__init__.py"),
    ("model_y.runtime", "model_y/runtime.py"),
    ("model_y.materials", "model_y/materials.py"),
    ("model_y.screen_driver", "model_y/screen_driver.py"),
    ("model_y.builder", "model_y/builder.py"),
    ("model_y.rig", "model_y/rig.py"),
]

LOADER = '''"""Generated by tools/bundle_for_blender.py -- do not edit by hand."""

import sys
import types

_SOURCES = _BUNDLE_SOURCES


def _install():
    """Rebuild the package in sys.modules, parents first, then exec each module."""
    package = types.ModuleType("model_y")
    package.__path__ = []          # marks it as a package so submodules import
    package.__package__ = "model_y"
    sys.modules["model_y"] = package
    for name in ("model_y.geom", "model_y.ui"):
        sub = types.ModuleType(name)
        sub.__path__ = []
        sub.__package__ = name
        sys.modules[name] = sub
        setattr(package, name.rsplit(".", 1)[1], sub)

    for name, source in _SOURCES:
        module = sys.modules.get(name)
        if module is None:
            module = types.ModuleType(name)
            module.__package__ = name.rsplit(".", 1)[0]
            sys.modules[name] = module
        module.__file__ = "<bundled %s>" % name
        exec(compile(source, "<bundled %s>" % name, "exec"), module.__dict__)
        parent = sys.modules.get(name.rsplit(".", 1)[0])
        if parent is not None:
            setattr(parent, name.rsplit(".", 1)[1], module)
    return package


model_y = _install()
'''

ENTRIES = {
    "scene": '''
# ---------------------------------------------------------------------------
# entry point: build the car, paint the screen, report what was made
# ---------------------------------------------------------------------------
from model_y import builder, rig, runtime, screen_driver  # noqa: E402
from model_y.specs import SPEC  # noqa: E402

PAINT = _PAINT
objects = builder.build_scene(paint=PAINT, interior=True, studio=_STUDIO)
runtime.STATE.gear = "P"
rig.RIG.reset()
rig.update(runtime.STATE, 0.0, objects)
screen_driver.refresh_screen("home", force=True)

import bpy  # noqa: E402

_body = objects["ModelY_Body"]
_dims = [round(v, 4) for v in _body.dimensions] if hasattr(_body, "dimensions") else []
result = {
    "objects": sorted(objects),
    "body_dimensions_m": _dims,
    "polygons": sum(len(o.data.polygons) for o in objects.values()
                    if getattr(o, "data", None) is not None
                    and hasattr(o.data, "polygons")),
    "materials": sorted(bpy.data.materials.keys()),
    "screen_pixels_lit": sum(1 for v in bpy.data.images["ModelY_Screen"].pixels[:40000]
                             if v > 0.02),
    "spec": SPEC.name,
}
''',
    "preview": '''
from model_y import builder, rig, runtime, screen_driver  # noqa: E402
objects = builder.build_scene(paint=_PAINT, interior=True, studio=_STUDIO)
rig.update(runtime.STATE, 0.0, objects)
screen_driver.refresh_screen("home", force=True)
result = {"built": len(objects)}
''',
}


def minify(source: str) -> str:
    """Drop comments, docstrings and blank lines; keep the code identical.

    Only used when the bundle has to travel through a channel that charges by
    the byte (a remote worker's single code field).  Indentation and every
    statement survive untouched, so tracebacks still point at real lines.
    """
    out: list[str] = []
    prev_end = (1, 0)
    prev_type = tokenize.INDENT
    depth = 0
    readline = io.StringIO(source).readline
    for tok in tokenize.generate_tokens(readline):
        ttype, text, start, end, _ = tok
        if ttype == tokenize.OP and text in "([{":
            depth += 1
        elif ttype == tokenize.OP and text in ")]}":
            depth -= 1
        if ttype == tokenize.COMMENT:
            prev_end = end
            continue
        # a string on its own at statement level is a docstring; one inside
        # brackets is a dict key or an argument, and has to stay
        if ttype == tokenize.STRING and depth == 0 and prev_type in (
                tokenize.INDENT, tokenize.NEWLINE, tokenize.DEDENT,
                tokenize.ENCODING):
            prev_type = ttype       # a bare string statement: a docstring
            prev_end = end
            continue
        if ttype == tokenize.NL and (not out or out[-1].endswith("\n")):
            continue
        if start[0] > prev_end[0]:
            if prev_type in (tokenize.NEWLINE, tokenize.NL, tokenize.INDENT,
                             tokenize.DEDENT, tokenize.ENCODING):
                out.append("\n" * (1 if ttype != tokenize.NEWLINE else 0))
                out.append(" " * start[1])
            else:
                # a continued logical line (inside brackets, or a backslash
                # continuation that is not a token at all): join it up
                out.append(" ")
        elif start[1] > prev_end[1]:
            out.append(" " * (start[1] - prev_end[1]))
        out.append(text)
        prev_type, prev_end = ttype, end
    text = "".join(out)
    return re.sub(r"\n\s*\n+", "\n", text)


def bundle(entry: str = "scene", paint: str = "Deep Blue Metallic",
           studio: bool = True, compact: bool = False) -> str:
    chunks = []
    for name, path in MODULES:
        with open(os.path.join(ROOT, path), encoding="utf-8") as fh:
            source = fh.read()
        chunks.append((name, minify(source) if compact else source))
    sources = "[\n" + "".join(
        f"    ({name!r}, {src!r}),\n" for name, src in chunks) + "]"
    body = ENTRIES[entry].replace("_PAINT", repr(paint)).replace("_STUDIO", repr(studio))
    return LOADER.replace("_BUNDLE_SOURCES", sources) + body


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.join(ROOT, "build", "model_y_bundle.py"))
    ap.add_argument("--entry", default="scene", choices=sorted(ENTRIES))
    ap.add_argument("--paint", default="Deep Blue Metallic")
    ap.add_argument("--no-studio", action="store_true")
    ap.add_argument("--compact", action="store_true",
                    help="strip comments and docstrings to shrink the payload")
    args = ap.parse_args()
    text = bundle(args.entry, args.paint, not args.no_studio, args.compact)
    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write(text)
    print(f"wrote {args.out} ({len(text):,} bytes, {len(MODULES)} modules)")


if __name__ == "__main__":
    main()
